"""Increase password_hash length to 256

Revision ID: ef1ff3aeabdc
Revises: 51f5ccfba190
Create Date: 2026-03-23 16:20:39.537883

"""

# revision identifiers, used by Alembic.
revision = 'ef1ff3aeabdc'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
